<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\CountryInfo;
use Illuminate\Database\Seeder;

/**
 * Seed CountryInfo pour les 110 pays qui n'ont pas pu être importés via
 * `countries:import-infos` (compte RESTCountries gelé + rate-limiting).
 *
 * Sources : données officielles / estimations ONU / Banque mondiale (2022–2024).
 */
class CountryInfoBulkSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->records() as $record) {
            $country = Country::query()->where('iso3', $record['iso3'])->first();

            if ($country === null) {
                $this->command?->warn("Pays introuvable : {$record['iso3']}");

                continue;
            }

            CountryInfo::updateOrCreate(
                ['country_id' => $country->id],
                [
                    'capital' => $record['capital'],
                    'languages' => $record['languages'],
                    'population' => $record['population'],
                    'currency' => $record['currency'],
                    'currency_code' => $record['currency_code'],
                    'population_year' => $record['population_year'],
                    'entity_type' => 'sovereign_state',
                    'parent_country' => null,
                ],
            );
        }
    }

    /**
     * @return array<int, array{
     *     iso3: string,
     *     capital: ?string,
     *     languages: ?array<int, array{code: ?string, name: string, native_name: ?string}>,
     *     population: ?int,
     *     currency: ?string,
     *     currency_code: ?string,
     *     population_year: ?int
     * }>
     */
    private function records(): array
    {
        return [
            [
                'iso3' => 'AFG',
                'capital' => 'Kaboul',
                'languages' => [
                    ['code' => 'fa', 'name' => 'Dari', 'native_name' => 'دری'],
                    ['code' => 'ps', 'name' => 'Pachto', 'native_name' => 'پښتو'],
                ],
                'population' => 43_844_000,
                'currency' => 'afghani afghan',
                'currency_code' => 'AFN',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'ZAF',
                'capital' => 'Pretoria',
                'languages' => [
                    ['code' => 'zu', 'name' => 'Zoulou', 'native_name' => 'isiZulu'],
                    ['code' => 'xh', 'name' => 'Xhosa', 'native_name' => 'isiXhosa'],
                    ['code' => 'af', 'name' => 'Afrikaans', 'native_name' => 'Afrikaans'],
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                    ['code' => 'st', 'name' => 'Sotho du Sud', 'native_name' => 'Sesotho'],
                    ['code' => 'tn', 'name' => 'Tswana', 'native_name' => 'Setswana'],
                    ['code' => 'ts', 'name' => 'Tsonga', 'native_name' => 'Xitsonga'],
                ],
                'population' => 63_015_904,
                'currency' => 'rand sud-africain',
                'currency_code' => 'ZAR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'ALB',
                'capital' => 'Tirana',
                'languages' => [
                    ['code' => 'sq', 'name' => 'Albanais', 'native_name' => 'shqip'],
                ],
                'population' => 2_335_930,
                'currency' => 'lek albanais',
                'currency_code' => 'ALL',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'DZA',
                'capital' => 'Alger',
                'languages' => [
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                    ['code' => null, 'name' => 'Tamazight', 'native_name' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
                ],
                'population' => 47_400_000,
                'currency' => 'dinar algérien',
                'currency_code' => 'DZD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'DEU',
                'capital' => 'Berlin',
                'languages' => [
                    ['code' => 'de', 'name' => 'Allemand', 'native_name' => 'Deutsch'],
                ],
                'population' => 83_467_117,
                'currency' => 'euro',
                'currency_code' => 'EUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BHR',
                'capital' => 'Manama',
                'languages' => [
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                ],
                'population' => 1_603_260,
                'currency' => 'dinar bahreïni',
                'currency_code' => 'BHD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BGD',
                'capital' => 'Dacca',
                'languages' => [
                    ['code' => 'bn', 'name' => 'Bengali', 'native_name' => 'বাংলা'],
                ],
                'population' => 169_828_911,
                'currency' => 'taka bangladais',
                'currency_code' => 'BDT',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BRB',
                'capital' => 'Bridgetown',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 261_692,
                'currency' => 'dollar de la Barbade',
                'currency_code' => 'BBD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BLR',
                'capital' => 'Minsk',
                'languages' => [
                    ['code' => 'be', 'name' => 'Biélorusse', 'native_name' => 'беларуская'],
                    ['code' => 'ru', 'name' => 'Russe', 'native_name' => 'русский'],
                ],
                'population' => 9_056_080,
                'currency' => 'rouble biélorusse',
                'currency_code' => 'BYN',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BEL',
                'capital' => 'Bruxelles',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                    ['code' => 'nl', 'name' => 'Néerlandais', 'native_name' => 'Nederlands'],
                    ['code' => 'de', 'name' => 'Allemand', 'native_name' => 'Deutsch'],
                ],
                'population' => 11_942_772,
                'currency' => 'euro',
                'currency_code' => 'EUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BLZ',
                'capital' => 'Belmopan',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 418_982,
                'currency' => 'dollar de Belize',
                'currency_code' => 'BZD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BEN',
                'capital' => 'Porto-Novo',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                ],
                'population' => 13_551_992,
                'currency' => "franc CFA d'Afrique de l'Ouest",
                'currency_code' => 'XOF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BTN',
                'capital' => 'Thimphu',
                'languages' => [
                    ['code' => 'dz', 'name' => 'Dzongkha', 'native_name' => 'རྫོང་ཁ'],
                ],
                'population' => 790_718,
                'currency' => 'ngultrum bhoutanais',
                'currency_code' => 'BTN',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BOL',
                'capital' => 'Sucre',
                'languages' => [
                    ['code' => 'es', 'name' => 'Espagnol', 'native_name' => 'español'],
                    ['code' => 'ay', 'name' => 'Aymara', 'native_name' => 'aymar aru'],
                    ['code' => 'qu', 'name' => 'Quechua', 'native_name' => 'Runa Simi'],
                ],
                'population' => 11_365_333,
                'currency' => 'boliviano',
                'currency_code' => 'BOB',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BIH',
                'capital' => 'Sarajevo',
                'languages' => [
                    ['code' => 'bs', 'name' => 'Bosnien', 'native_name' => 'bosanski'],
                    ['code' => 'sr', 'name' => 'Serbe', 'native_name' => 'српски'],
                    ['code' => 'hr', 'name' => 'Croate', 'native_name' => 'hrvatski'],
                ],
                'population' => 3_412_000,
                'currency' => 'mark convertible de Bosnie-Herzégovine',
                'currency_code' => 'BAM',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BWA',
                'capital' => 'Gaborone',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                    ['code' => 'tn', 'name' => 'Tswana', 'native_name' => 'Setswana'],
                ],
                'population' => 2_359_609,
                'currency' => 'pula botswanais',
                'currency_code' => 'BWP',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BRA',
                'capital' => 'Brasília',
                'languages' => [
                    ['code' => 'pt', 'name' => 'Portugais', 'native_name' => 'português'],
                ],
                'population' => 214_211_951,
                'currency' => 'réal brésilien',
                'currency_code' => 'BRL',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BRN',
                'capital' => 'Bandar Seri Begawan',
                'languages' => [
                    ['code' => 'ms', 'name' => 'Malais', 'native_name' => 'Bahasa Melayu'],
                ],
                'population' => 444_769,
                'currency' => 'dollar de Brunei',
                'currency_code' => 'BND',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BGR',
                'capital' => 'Sofia',
                'languages' => [
                    ['code' => 'bg', 'name' => 'Bulgare', 'native_name' => 'български'],
                ],
                'population' => 7_127_724,
                'currency' => 'lev bulgare',
                'currency_code' => 'BGN',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BFA',
                'capital' => 'Ouagadougou',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                ],
                'population' => 22_100_683,
                'currency' => "franc CFA d'Afrique de l'Ouest",
                'currency_code' => 'XOF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'BDI',
                'capital' => 'Gitega',
                'languages' => [
                    ['code' => 'rn', 'name' => 'Kirundi', 'native_name' => 'Ikirundi'],
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 12_745_573,
                'currency' => 'franc burundais',
                'currency_code' => 'BIF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'COM',
                'capital' => 'Moroni',
                'languages' => [
                    ['code' => null, 'name' => 'Comorien', 'native_name' => 'Shikomori'],
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                ],
                'population' => 819_078,
                'currency' => 'franc comorien',
                'currency_code' => 'KMF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'COG',
                'capital' => 'Brazzaville',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                    ['code' => 'ln', 'name' => 'Lingala', 'native_name' => 'lingála'],
                    ['code' => 'kg', 'name' => 'Kongo', 'native_name' => 'Kikongo'],
                ],
                'population' => 6_144_945,
                'currency' => "franc CFA d'Afrique centrale",
                'currency_code' => 'XAF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'COD',
                'capital' => 'Kinshasa',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                    ['code' => 'ln', 'name' => 'Lingala', 'native_name' => 'lingála'],
                    ['code' => 'kg', 'name' => 'Kongo', 'native_name' => 'Kikongo'],
                    ['code' => 'sw', 'name' => 'Swahili', 'native_name' => 'Kiswahili'],
                ],
                'population' => 99_010_212,
                'currency' => 'franc congolais',
                'currency_code' => 'CDF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'PRK',
                'capital' => 'Pyongyang',
                'languages' => [
                    ['code' => 'ko', 'name' => 'Coréen', 'native_name' => '한국어'],
                ],
                'population' => 25_970_000,
                'currency' => 'won nord-coréen',
                'currency_code' => 'KPW',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'KOR',
                'capital' => 'Séoul',
                'languages' => [
                    ['code' => 'ko', 'name' => 'Coréen', 'native_name' => '한국어'],
                ],
                'population' => 51_995_923,
                'currency' => 'won sud-coréen',
                'currency_code' => 'KRW',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'CRI',
                'capital' => 'San José',
                'languages' => [
                    ['code' => 'es', 'name' => 'Espagnol', 'native_name' => 'español'],
                ],
                'population' => 5_180_829,
                'currency' => 'colón costaricain',
                'currency_code' => 'CRC',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'CIV',
                'capital' => 'Yamoussoukro',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                ],
                'population' => 27_742_974,
                'currency' => "franc CFA d'Afrique de l'Ouest",
                'currency_code' => 'XOF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'HRV',
                'capital' => 'Zagreb',
                'languages' => [
                    ['code' => 'hr', 'name' => 'Croate', 'native_name' => 'hrvatski'],
                ],
                'population' => 3_869_000,
                'currency' => 'euro',
                'currency_code' => 'EUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'CUB',
                'capital' => 'La Havane',
                'languages' => [
                    ['code' => 'es', 'name' => 'Espagnol', 'native_name' => 'español'],
                ],
                'population' => 11_347_897,
                'currency' => 'peso cubain',
                'currency_code' => 'CUP',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'DNK',
                'capital' => 'Copenhague',
                'languages' => [
                    ['code' => 'da', 'name' => 'Danois', 'native_name' => 'dansk'],
                ],
                'population' => 5_973_136,
                'currency' => 'couronne danoise',
                'currency_code' => 'DKK',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'DJI',
                'capital' => 'Djibouti',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                ],
                'population' => 1_136_455,
                'currency' => 'franc djiboutien',
                'currency_code' => 'DJF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'DMA',
                'capital' => 'Roseau',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 71_986,
                'currency' => 'dollar des Caraïbes orientales',
                'currency_code' => 'XCD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'EGY',
                'capital' => 'Le Caire',
                'languages' => [
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                ],
                'population' => 104_258_327,
                'currency' => 'livre égyptienne',
                'currency_code' => 'EGP',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'ARE',
                'capital' => 'Abou Dabi',
                'languages' => [
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                ],
                'population' => 10_044_649,
                'currency' => 'dirham des Émirats arabes unis',
                'currency_code' => 'AED',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'GMB',
                'capital' => 'Banjul',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 2_639_916,
                'currency' => 'dalasi gambien',
                'currency_code' => 'GMD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'GEO',
                'capital' => 'Tbilissi',
                'languages' => [
                    ['code' => 'ka', 'name' => 'Géorgien', 'native_name' => 'ქართული'],
                ],
                'population' => 3_744_090,
                'currency' => 'lari géorgien',
                'currency_code' => 'GEL',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'GHA',
                'capital' => 'Accra',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 34_121_985,
                'currency' => 'cedi ghanéen',
                'currency_code' => 'GHS',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'GRC',
                'capital' => 'Athènes',
                'languages' => [
                    ['code' => 'el', 'name' => 'Grec', 'native_name' => 'ελληνικά'],
                ],
                'population' => 10_432_481,
                'currency' => 'euro',
                'currency_code' => 'EUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'GRD',
                'capital' => 'Saint-George\'s',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 123_246,
                'currency' => 'dollar des Caraïbes orientales',
                'currency_code' => 'XCD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'GTM',
                'capital' => 'Guatemala',
                'languages' => [
                    ['code' => 'es', 'name' => 'Espagnol', 'native_name' => 'español'],
                ],
                'population' => 17_843_908,
                'currency' => 'quetzal guatémaltèque',
                'currency_code' => 'GTQ',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'GIN',
                'capital' => 'Conakry',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                ],
                'population' => 13_859_025,
                'currency' => 'franc guinéen',
                'currency_code' => 'GNF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'GNQ',
                'capital' => 'Malabo',
                'languages' => [
                    ['code' => 'es', 'name' => 'Espagnol', 'native_name' => 'español'],
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                    ['code' => 'pt', 'name' => 'Portugais', 'native_name' => 'português'],
                ],
                'population' => 1_496_968,
                'currency' => "franc CFA d'Afrique centrale",
                'currency_code' => 'XAF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'GNB',
                'capital' => 'Bissau',
                'languages' => [
                    ['code' => 'pt', 'name' => 'Portugais', 'native_name' => 'português'],
                ],
                'population' => 2_106_267,
                'currency' => "franc CFA d'Afrique de l'Ouest",
                'currency_code' => 'XOF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'GUY',
                'capital' => 'Georgetown',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 791_568,
                'currency' => 'dollar guyanien',
                'currency_code' => 'GYD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'HTI',
                'capital' => 'Port-au-Prince',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                    ['code' => 'ht', 'name' => 'Créole haïtien', 'native_name' => 'Kreyòl ayisyen'],
                ],
                'population' => 11_609_426,
                'currency' => 'gourde haïtienne',
                'currency_code' => 'HTG',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'HND',
                'capital' => 'Tegucigalpa',
                'languages' => [
                    ['code' => 'es', 'name' => 'Espagnol', 'native_name' => 'español'],
                ],
                'population' => 10_280_862,
                'currency' => 'lempira hondurien',
                'currency_code' => 'HNL',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'HUN',
                'capital' => 'Budapest',
                'languages' => [
                    ['code' => 'hu', 'name' => 'Hongrois', 'native_name' => 'magyar'],
                ],
                'population' => 9_749_763,
                'currency' => 'forint hongrois',
                'currency_code' => 'HUF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MHL',
                'capital' => 'Majuro',
                'languages' => [
                    ['code' => 'mh', 'name' => 'Marshallais', 'native_name' => 'Kajin M̧ajeļ'],
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 41_569,
                'currency' => 'dollar américain',
                'currency_code' => 'USD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'IND',
                'capital' => 'New Delhi',
                'languages' => [
                    ['code' => 'hi', 'name' => 'Hindi', 'native_name' => 'हिन्दी'],
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 1_407_563_842,
                'currency' => 'roupie indienne',
                'currency_code' => 'INR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MWI',
                'capital' => 'Lilongwe',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                    ['code' => 'ny', 'name' => 'Chichewa', 'native_name' => 'chiCheŵa'],
                ],
                'population' => 20_405_317,
                'currency' => 'kwacha malawite',
                'currency_code' => 'MWK',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MDV',
                'capital' => 'Malé',
                'languages' => [
                    ['code' => 'dv', 'name' => 'Maldivien', 'native_name' => 'ދިވެހި'],
                ],
                'population' => 536_978,
                'currency' => 'rufiyaa maldivienne',
                'currency_code' => 'MVR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MLI',
                'capital' => 'Bamako',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                ],
                'population' => 22_414_220,
                'currency' => "franc CFA d'Afrique de l'Ouest",
                'currency_code' => 'XOF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MLT',
                'capital' => 'La Valette',
                'languages' => [
                    ['code' => 'mt', 'name' => 'Maltais', 'native_name' => 'Malti'],
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 537_000,
                'currency' => 'euro',
                'currency_code' => 'EUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MAR',
                'capital' => 'Rabat',
                'languages' => [
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                    ['code' => null, 'name' => 'Tamazight marocain', 'native_name' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
                ],
                'population' => 37_457_971,
                'currency' => 'dirham marocain',
                'currency_code' => 'MAD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MUS',
                'capital' => 'Port-Louis',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                    ['code' => null, 'name' => 'Créole mauricien', 'native_name' => 'Morisien'],
                ],
                'population' => 1_296_303,
                'currency' => 'roupie mauricienne',
                'currency_code' => 'MUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MRT',
                'capital' => 'Nouakchott',
                'languages' => [
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                ],
                'population' => 4_649_658,
                'currency' => 'ouguiya mauritanien',
                'currency_code' => 'MRU',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MEX',
                'capital' => 'Mexico',
                'languages' => [
                    ['code' => 'es', 'name' => 'Espagnol', 'native_name' => 'español'],
                ],
                'population' => 130_262_216,
                'currency' => 'peso mexicain',
                'currency_code' => 'MXN',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'FSM',
                'capital' => 'Palikir',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 117_489,
                'currency' => 'dollar américain',
                'currency_code' => 'USD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MDA',
                'capital' => 'Chișinău',
                'languages' => [
                    ['code' => 'ro', 'name' => 'Roumain', 'native_name' => 'română'],
                ],
                'population' => 2_498_000,
                'currency' => 'leu moldave',
                'currency_code' => 'MDL',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MCO',
                'capital' => 'Monaco',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                ],
                'population' => 36_469,
                'currency' => 'euro',
                'currency_code' => 'EUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MNG',
                'capital' => 'Oulan-Bator',
                'languages' => [
                    ['code' => 'mn', 'name' => 'Mongol', 'native_name' => 'монгол хэл'],
                ],
                'population' => 3_398_366,
                'currency' => 'tugrik mongol',
                'currency_code' => 'MNT',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MNE',
                'capital' => 'Podgorica',
                'languages' => [
                    ['code' => 'sr', 'name' => 'Monténégrin', 'native_name' => 'crnogorski'],
                ],
                'population' => 619_211,
                'currency' => 'euro',
                'currency_code' => 'EUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MOZ',
                'capital' => 'Maputo',
                'languages' => [
                    ['code' => 'pt', 'name' => 'Portugais', 'native_name' => 'português'],
                ],
                'population' => 33_089_461,
                'currency' => 'metical mozambicain',
                'currency_code' => 'MZN',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'MMR',
                'capital' => 'Naypyidaw',
                'languages' => [
                    ['code' => 'my', 'name' => 'Birman', 'native_name' => 'မြန်မာဘာသာ'],
                ],
                'population' => 54_409_800,
                'currency' => 'kyat birman',
                'currency_code' => 'MMK',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'NAM',
                'capital' => 'Windhoek',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                    ['code' => 'af', 'name' => 'Afrikaans', 'native_name' => 'Afrikaans'],
                ],
                'population' => 2_550_226,
                'currency' => 'dollar namibien',
                'currency_code' => 'NAD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'KNA',
                'capital' => 'Basseterre',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 53_192,
                'currency' => 'dollar des Caraïbes orientales',
                'currency_code' => 'XCD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SMR',
                'capital' => 'Saint-Marin',
                'languages' => [
                    ['code' => 'it', 'name' => 'Italien', 'native_name' => 'italiano'],
                ],
                'population' => 34_017,
                'currency' => 'euro',
                'currency_code' => 'EUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'VCT',
                'capital' => 'Kingstown',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 104_332,
                'currency' => 'dollar des Caraïbes orientales',
                'currency_code' => 'XCD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'LCA',
                'capital' => 'Castries',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 179_651,
                'currency' => 'dollar des Caraïbes orientales',
                'currency_code' => 'XCD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SLB',
                'capital' => 'Honiara',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 740_424,
                'currency' => 'dollar des Salomon',
                'currency_code' => 'SBD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SLV',
                'capital' => 'San Salvador',
                'languages' => [
                    ['code' => 'es', 'name' => 'Espagnol', 'native_name' => 'español'],
                ],
                'population' => 6_314_167,
                'currency' => 'dollar américain',
                'currency_code' => 'USD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'WSM',
                'capital' => 'Apia',
                'languages' => [
                    ['code' => 'sm', 'name' => 'Samoan', 'native_name' => 'gagana faʻa Sāmoa'],
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 222_382,
                'currency' => 'tālā samoan',
                'currency_code' => 'WST',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'STP',
                'capital' => 'São Tomé',
                'languages' => [
                    ['code' => 'pt', 'name' => 'Portugais', 'native_name' => 'português'],
                ],
                'population' => 223_369,
                'currency' => 'dobra de São Tomé-et-Príncipe',
                'currency_code' => 'STN',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SEN',
                'capital' => 'Dakar',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                ],
                'population' => 17_735_022,
                'currency' => "franc CFA d'Afrique de l'Ouest",
                'currency_code' => 'XOF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SRB',
                'capital' => 'Belgrade',
                'languages' => [
                    ['code' => 'sr', 'name' => 'Serbe', 'native_name' => 'српски'],
                ],
                'population' => 6_981_083,
                'currency' => 'dinar serbe',
                'currency_code' => 'RSD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SYC',
                'capital' => 'Victoria',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                    ['code' => null, 'name' => 'Créole seychellois', 'native_name' => 'Kreol seselwa'],
                ],
                'population' => 107_118,
                'currency' => 'roupie des Seychelles',
                'currency_code' => 'SCR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SLE',
                'capital' => 'Freetown',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 7_976_983,
                'currency' => 'leone sierra-léonais',
                'currency_code' => 'SLE',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SGP',
                'capital' => 'Singapour',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                    ['code' => 'ms', 'name' => 'Malais', 'native_name' => 'Bahasa Melayu'],
                    ['code' => 'ta', 'name' => 'Tamoul', 'native_name' => 'தமிழ்'],
                    ['code' => 'zh', 'name' => 'Chinois', 'native_name' => '中文'],
                ],
                'population' => 5_917_648,
                'currency' => 'dollar de Singapour',
                'currency_code' => 'SGD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SVK',
                'capital' => 'Bratislava',
                'languages' => [
                    ['code' => 'sk', 'name' => 'Slovaque', 'native_name' => 'slovenčina'],
                ],
                'population' => 5_460_184,
                'currency' => 'euro',
                'currency_code' => 'EUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SVN',
                'capital' => 'Ljubljana',
                'languages' => [
                    ['code' => 'sl', 'name' => 'Slovène', 'native_name' => 'slovenščina'],
                ],
                'population' => 2_116_792,
                'currency' => 'euro',
                'currency_code' => 'EUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SOM',
                'capital' => 'Mogadiscio',
                'languages' => [
                    ['code' => 'so', 'name' => 'Somali', 'native_name' => 'Soomaali'],
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                ],
                'population' => 17_590_502,
                'currency' => 'shilling somalien',
                'currency_code' => 'SOS',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SDN',
                'capital' => 'Khartoum',
                'languages' => [
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 46_874_204,
                'currency' => 'livre soudanaise',
                'currency_code' => 'SDG',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SSD',
                'capital' => 'Djouba',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 10_748_272,
                'currency' => 'livre sud-soudanaise',
                'currency_code' => 'SSP',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'LKA',
                'capital' => 'Sri Jayawardenepura Kotte',
                'languages' => [
                    ['code' => 'si', 'name' => 'Cingalais', 'native_name' => 'සිංහල'],
                    ['code' => 'ta', 'name' => 'Tamoul', 'native_name' => 'தமிழ்'],
                ],
                'population' => 23_044_123,
                'currency' => 'roupie sri-lankaise',
                'currency_code' => 'LKR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SWE',
                'capital' => 'Stockholm',
                'languages' => [
                    ['code' => 'sv', 'name' => 'Suédois', 'native_name' => 'svenska'],
                ],
                'population' => 10_612_975,
                'currency' => 'couronne suédoise',
                'currency_code' => 'SEK',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'CHE',
                'capital' => 'Berne',
                'languages' => [
                    ['code' => 'de', 'name' => 'Allemand', 'native_name' => 'Deutsch'],
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                    ['code' => 'it', 'name' => 'Italien', 'native_name' => 'italiano'],
                    ['code' => 'rm', 'name' => 'Romanche', 'native_name' => 'Rumantsch'],
                ],
                'population' => 8_925_000,
                'currency' => 'franc suisse',
                'currency_code' => 'CHF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SUR',
                'capital' => 'Paramaribo',
                'languages' => [
                    ['code' => 'nl', 'name' => 'Néerlandais', 'native_name' => 'Nederlands'],
                ],
                'population' => 623_236,
                'currency' => 'dollar du Suriname',
                'currency_code' => 'SRD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'SYR',
                'capital' => 'Damas',
                'languages' => [
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                ],
                'population' => 21_324_367,
                'currency' => 'livre syrienne',
                'currency_code' => 'SYP',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'TJK',
                'capital' => 'Douchanbé',
                'languages' => [
                    ['code' => 'tg', 'name' => 'Tadjik', 'native_name' => 'тоҷикӣ'],
                    ['code' => 'ru', 'name' => 'Russe', 'native_name' => 'русский'],
                ],
                'population' => 10_143_543,
                'currency' => 'somoni tadjik',
                'currency_code' => 'TJS',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'TZA',
                'capital' => 'Dodoma',
                'languages' => [
                    ['code' => 'sw', 'name' => 'Swahili', 'native_name' => 'Kiswahili'],
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 65_497_748,
                'currency' => 'shilling tanzanien',
                'currency_code' => 'TZS',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'TCD',
                'capital' => "N'Djaména",
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                ],
                'population' => 18_523_890,
                'currency' => "franc CFA d'Afrique centrale",
                'currency_code' => 'XAF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'THA',
                'capital' => 'Bangkok',
                'languages' => [
                    ['code' => 'th', 'name' => 'Thaï', 'native_name' => 'ภาษาไทย'],
                ],
                'population' => 69_648_117,
                'currency' => 'baht thaïlandais',
                'currency_code' => 'THB',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'TLS',
                'capital' => 'Dili',
                'languages' => [
                    ['code' => null, 'name' => 'Tétoum', 'native_name' => 'Tetum'],
                    ['code' => 'pt', 'name' => 'Portugais', 'native_name' => 'português'],
                ],
                'population' => 1_340_513,
                'currency' => 'dollar américain',
                'currency_code' => 'USD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'TGO',
                'capital' => 'Lomé',
                'languages' => [
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                ],
                'population' => 9_053_799,
                'currency' => "franc CFA d'Afrique de l'Ouest",
                'currency_code' => 'XOF',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'TON',
                'capital' => "Nuku'alofa",
                'languages' => [
                    ['code' => 'to', 'name' => 'Tongien', 'native_name' => 'lea fakatonga'],
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 105_695,
                'currency' => 'paʻanga tongien',
                'currency_code' => 'TOP',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'TTO',
                'capital' => "Port d'Espagne",
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 1_394_969,
                'currency' => 'dollar de Trinité-et-Tobago',
                'currency_code' => 'TTD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'TUN',
                'capital' => 'Tunis',
                'languages' => [
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                ],
                'population' => 12_356_117,
                'currency' => 'dinar tunisien',
                'currency_code' => 'TND',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'TKM',
                'capital' => 'Achgabat',
                'languages' => [
                    ['code' => 'tk', 'name' => 'Turkmène', 'native_name' => 'Türkmen'],
                    ['code' => 'ru', 'name' => 'Russe', 'native_name' => 'русский'],
                ],
                'population' => 6_341_855,
                'currency' => 'manat turkmène',
                'currency_code' => 'TMT',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'TUR',
                'capital' => 'Ankara',
                'languages' => [
                    ['code' => 'tr', 'name' => 'Turc', 'native_name' => 'Türkçe'],
                ],
                'population' => 85_341_241,
                'currency' => 'lire turque',
                'currency_code' => 'TRY',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'TUV',
                'capital' => 'Funafuti',
                'languages' => [
                    ['code' => null, 'name' => 'Tuvaluan', 'native_name' => 'Gagana Tuvalu'],
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 11_204,
                'currency' => 'dollar australien',
                'currency_code' => 'AUD',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'UKR',
                'capital' => 'Kiev',
                'languages' => [
                    ['code' => 'uk', 'name' => 'Ukrainien', 'native_name' => 'українська'],
                ],
                'population' => 43_531_422,
                'currency' => 'hryvnia ukrainienne',
                'currency_code' => 'UAH',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'URY',
                'capital' => 'Montevideo',
                'languages' => [
                    ['code' => 'es', 'name' => 'Espagnol', 'native_name' => 'español'],
                ],
                'population' => 3_685_094,
                'currency' => 'peso uruguayen',
                'currency_code' => 'UYU',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'VUT',
                'capital' => 'Port-Vila',
                'languages' => [
                    ['code' => 'bi', 'name' => 'Bichelamar', 'native_name' => 'Bislama'],
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                    ['code' => 'fr', 'name' => 'Français', 'native_name' => 'français'],
                ],
                'population' => 332_786,
                'currency' => 'vatu vanuatuan',
                'currency_code' => 'VUV',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'VAT',
                'capital' => 'Cité du Vatican',
                'languages' => [
                    ['code' => 'la', 'name' => 'Latin', 'native_name' => 'Latine'],
                    ['code' => 'it', 'name' => 'Italien', 'native_name' => 'italiano'],
                ],
                'population' => 799,
                'currency' => 'euro',
                'currency_code' => 'EUR',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'VEN',
                'capital' => 'Caracas',
                'languages' => [
                    ['code' => 'es', 'name' => 'Espagnol', 'native_name' => 'español'],
                ],
                'population' => 30_518_260,
                'currency' => 'bolívar vénézuélien',
                'currency_code' => 'VES',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'VNM',
                'capital' => 'Hanoï',
                'languages' => [
                    ['code' => 'vi', 'name' => 'Vietnamien', 'native_name' => 'Tiếng Việt'],
                ],
                'population' => 98_186_463,
                'currency' => 'dong vietnamien',
                'currency_code' => 'VND',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'YEM',
                'capital' => 'Sanaa',
                'languages' => [
                    ['code' => 'ar', 'name' => 'Arabe', 'native_name' => 'العربية'],
                ],
                'population' => 34_449_825,
                'currency' => 'rial yéménite',
                'currency_code' => 'YER',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'ZMB',
                'capital' => 'Lusaka',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                ],
                'population' => 20_017_675,
                'currency' => 'kwacha zambien',
                'currency_code' => 'ZMW',
                'population_year' => 2024,
            ],
            [
                'iso3' => 'ZWE',
                'capital' => 'Harare',
                'languages' => [
                    ['code' => 'en', 'name' => 'Anglais', 'native_name' => 'English'],
                    ['code' => 'sn', 'name' => 'Shona', 'native_name' => 'chiShona'],
                    ['code' => 'nd', 'name' => 'Ndébélé du Nord', 'native_name' => 'isiNdebele'],
                ],
                'population' => 15_178_979,
                'currency' => 'dollar zimbabwéen',
                'currency_code' => 'ZWL',
                'population_year' => 2024,
            ],
        ];
    }
}
