<?php

namespace Database\Seeders;

use App\Models\Continent;
use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $continents = Continent::all()->keyBy('slug');

        $countries = [
            'afrique' => [
                ['name' => 'Algérie', 'iso3' => 'DZA', 'latitude' => 28.0, 'longitude' => 3.0],
                ['name' => 'Angola', 'iso3' => 'AGO', 'latitude' => -11.2, 'longitude' => 17.9],
                ['name' => 'Bénin', 'iso3' => 'BEN', 'latitude' => 9.3, 'longitude' => 2.3],
                ['name' => 'Botswana', 'iso3' => 'BWA', 'latitude' => -22.3, 'longitude' => 24.7],
                ['name' => 'Burkina Faso', 'iso3' => 'BFA', 'latitude' => 12.4, 'longitude' => -1.6],
                ['name' => 'Burundi', 'iso3' => 'BDI', 'latitude' => -3.4, 'longitude' => 29.9],
                ['name' => 'Cameroun', 'iso3' => 'CMR', 'latitude' => 3.9, 'longitude' => 11.5],
                ['name' => 'Cap-Vert', 'iso3' => 'CPV', 'latitude' => 16.0, 'longitude' => -24.0],
                ['name' => 'République centrafricaine', 'iso3' => 'CAF', 'latitude' => 6.6, 'longitude' => 20.9],
                ['name' => 'Comores', 'iso3' => 'COM', 'latitude' => -11.6, 'longitude' => 43.3],
                ['name' => 'Congo (RDC)', 'iso3' => 'COD', 'latitude' => -4.0, 'longitude' => 21.8],
                ['name' => 'Congo', 'iso3' => 'COG', 'latitude' => -0.2, 'longitude' => 15.8],
                ['name' => "Côte d'Ivoire", 'iso3' => 'CIV', 'latitude' => 7.5, 'longitude' => -5.5],
                ['name' => 'Djibouti', 'iso3' => 'DJI', 'latitude' => 11.8, 'longitude' => 42.6],
                ['name' => 'Égypte', 'iso3' => 'EGY', 'latitude' => 26.8, 'longitude' => 30.8],
                ['name' => 'Érythrée', 'iso3' => 'ERI', 'latitude' => 15.2, 'longitude' => 39.8],
                ['name' => 'Éthiopie', 'iso3' => 'ETH', 'latitude' => 9.1, 'longitude' => 40.5],
                ['name' => 'Gabon', 'iso3' => 'GAB', 'latitude' => -0.8, 'longitude' => 11.6],
                ['name' => 'Gambie', 'iso3' => 'GMB', 'latitude' => 13.4, 'longitude' => -15.3],
                ['name' => 'Ghana', 'iso3' => 'GHA', 'latitude' => 7.9, 'longitude' => -1.0],
                ['name' => 'Guinée', 'iso3' => 'GIN', 'latitude' => 11.0, 'longitude' => -10.9],
                ['name' => 'Guinée-Bissau', 'iso3' => 'GNB', 'latitude' => 11.8, 'longitude' => -15.2],
                ['name' => 'Guinée équatoriale', 'iso3' => 'GNQ', 'latitude' => 1.6, 'longitude' => 10.3],
                ['name' => 'Kenya', 'iso3' => 'KEN', 'latitude' => -0.0, 'longitude' => 37.9],
                ['name' => 'Lesotho', 'iso3' => 'LSO', 'latitude' => -29.6, 'longitude' => 28.2],
                ['name' => 'Libéria', 'iso3' => 'LBR', 'latitude' => 6.4, 'longitude' => -9.4],
                ['name' => 'Libye', 'iso3' => 'LBY', 'latitude' => 26.3, 'longitude' => 17.2],
                ['name' => 'Madagascar', 'iso3' => 'MDG', 'latitude' => -20.0, 'longitude' => 47.0],
                ['name' => 'Malawi', 'iso3' => 'MWI', 'latitude' => -13.3, 'longitude' => 34.3],
                ['name' => 'Mali', 'iso3' => 'MLI', 'latitude' => 17.6, 'longitude' => -4.0],
                ['name' => 'Maroc', 'iso3' => 'MAR', 'latitude' => 31.8, 'longitude' => -7.1],
                ['name' => 'Maurice', 'iso3' => 'MUS', 'latitude' => -20.3, 'longitude' => 57.6],
                ['name' => 'Mauritanie', 'iso3' => 'MRT', 'latitude' => 21.0, 'longitude' => -10.9],
                ['name' => 'Mozambique', 'iso3' => 'MOZ', 'latitude' => -18.7, 'longitude' => 35.5],
                ['name' => 'Namibie', 'iso3' => 'NAM', 'latitude' => -22.0, 'longitude' => 17.1],
                ['name' => 'Niger', 'iso3' => 'NER', 'latitude' => 17.6, 'longitude' => 8.1],
                ['name' => 'Nigéria', 'iso3' => 'NGA', 'latitude' => 9.1, 'longitude' => 8.7],
                ['name' => 'Ouganda', 'iso3' => 'UGA', 'latitude' => 1.4, 'longitude' => 32.3],
                ['name' => 'Rwanda', 'iso3' => 'RWA', 'latitude' => -2.0, 'longitude' => 29.9],
                ['name' => 'Sao Tomé-et-Principe', 'iso3' => 'STP', 'latitude' => 0.2, 'longitude' => 6.6],
                ['name' => 'Sénégal', 'iso3' => 'SEN', 'latitude' => 14.5, 'longitude' => -14.5],
                ['name' => 'Seychelles', 'iso3' => 'SYC', 'latitude' => -4.7, 'longitude' => 55.5],
                ['name' => 'Sierra Leone', 'iso3' => 'SLE', 'latitude' => 8.5, 'longitude' => -11.8],
                ['name' => 'Somalie', 'iso3' => 'SOM', 'latitude' => 5.2, 'longitude' => 46.2],
                ['name' => 'Soudan', 'iso3' => 'SDN', 'latitude' => 12.9, 'longitude' => 30.2],
                ['name' => 'Soudan du Sud', 'iso3' => 'SSD', 'latitude' => 6.9, 'longitude' => 31.3],
                ['name' => 'Eswatini', 'iso3' => 'SWZ', 'latitude' => -26.5, 'longitude' => 31.5],
                ['name' => 'Tanzanie', 'iso3' => 'TZA', 'latitude' => -6.4, 'longitude' => 34.9],
                ['name' => 'Tchad', 'iso3' => 'TCD', 'latitude' => 15.5, 'longitude' => 18.7],
                ['name' => 'Togo', 'iso3' => 'TGO', 'latitude' => 8.6, 'longitude' => 0.8],
                ['name' => 'Tunisie', 'iso3' => 'TUN', 'latitude' => 33.9, 'longitude' => 9.5],
                ['name' => 'Afrique du Sud', 'iso3' => 'ZAF', 'latitude' => -30.6, 'longitude' => 22.9],
                ['name' => 'Zambie', 'iso3' => 'ZMB', 'latitude' => -13.1, 'longitude' => 27.8],
                ['name' => 'Zimbabwe', 'iso3' => 'ZWE', 'latitude' => -19.0, 'longitude' => 29.2],
            ],
            'amerique' => [
                ['name' => 'Antigua-et-Barbuda', 'iso3' => 'ATG', 'latitude' => 17.1, 'longitude' => -61.8],
                ['name' => 'Argentine', 'iso3' => 'ARG', 'latitude' => -38.4, 'longitude' => -63.6],
                ['name' => 'Bahamas', 'iso3' => 'BHS', 'latitude' => 25.0, 'longitude' => -77.4],
                ['name' => 'Barbade', 'iso3' => 'BRB', 'latitude' => 13.2, 'longitude' => -59.6],
                ['name' => 'Belize', 'iso3' => 'BLZ', 'latitude' => 17.2, 'longitude' => -88.5],
                ['name' => 'Bolivie', 'iso3' => 'BOL', 'latitude' => -16.3, 'longitude' => -63.6],
                ['name' => 'Brésil', 'iso3' => 'BRA', 'latitude' => -14.2, 'longitude' => -51.9],
                ['name' => 'Canada', 'iso3' => 'CAN', 'latitude' => 56.1, 'longitude' => -106.3],
                ['name' => 'Chili', 'iso3' => 'CHL', 'latitude' => -35.7, 'longitude' => -71.5],
                ['name' => 'Colombie', 'iso3' => 'COL', 'latitude' => 4.6, 'longitude' => -74.1],
                ['name' => 'Costa Rica', 'iso3' => 'CRI', 'latitude' => 9.7, 'longitude' => -83.8],
                ['name' => 'Cuba', 'iso3' => 'CUB', 'latitude' => 21.5, 'longitude' => -79.5],
                ['name' => 'Dominique', 'iso3' => 'DMA', 'latitude' => 15.4, 'longitude' => -61.4],
                ['name' => 'République dominicaine', 'iso3' => 'DOM', 'latitude' => 18.7, 'longitude' => -70.2],
                ['name' => 'Équateur', 'iso3' => 'ECU', 'latitude' => -1.8, 'longitude' => -78.2],
                ['name' => 'États-Unis', 'iso3' => 'USA', 'latitude' => 37.1, 'longitude' => -95.7],
                ['name' => 'Grenade', 'iso3' => 'GRD', 'latitude' => 12.1, 'longitude' => -61.7],
                ['name' => 'Guatemala', 'iso3' => 'GTM', 'latitude' => 15.8, 'longitude' => -90.2],
                ['name' => 'Guyana', 'iso3' => 'GUY', 'latitude' => 4.9, 'longitude' => -59.0],
                ['name' => 'Haïti', 'iso3' => 'HTI', 'latitude' => 18.9, 'longitude' => -72.3],
                ['name' => 'Honduras', 'iso3' => 'HND', 'latitude' => 15.2, 'longitude' => -86.2],
                ['name' => 'Jamaïque', 'iso3' => 'JAM', 'latitude' => 18.1, 'longitude' => -77.3],
                ['name' => 'Mexique', 'iso3' => 'MEX', 'latitude' => 23.6, 'longitude' => -102.6],
                ['name' => 'Nicaragua', 'iso3' => 'NIC', 'latitude' => 12.9, 'longitude' => -85.2],
                ['name' => 'Panama', 'iso3' => 'PAN', 'latitude' => 8.5, 'longitude' => -80.8],
                ['name' => 'Paraguay', 'iso3' => 'PRY', 'latitude' => -23.4, 'longitude' => -58.4],
                ['name' => 'Pérou', 'iso3' => 'PER', 'latitude' => -9.2, 'longitude' => -75.0],
                ['name' => 'Saint-Kitts-et-Nevis', 'iso3' => 'KNA', 'latitude' => 17.4, 'longitude' => -62.8],
                ['name' => 'Sainte-Lucie', 'iso3' => 'LCA', 'latitude' => 13.9, 'longitude' => -60.9],
                ['name' => 'Saint-Vincent-et-les-Grenadines', 'iso3' => 'VCT', 'latitude' => 13.3, 'longitude' => -61.2],
                ['name' => 'Salvador', 'iso3' => 'SLV', 'latitude' => 13.8, 'longitude' => -88.9],
                ['name' => 'Suriname', 'iso3' => 'SUR', 'latitude' => 3.9, 'longitude' => -56.0],
                ['name' => 'Trinité-et-Tobago', 'iso3' => 'TTO', 'latitude' => 10.7, 'longitude' => -61.2],
                ['name' => 'Uruguay', 'iso3' => 'URY', 'latitude' => -32.5, 'longitude' => -55.8],
                ['name' => 'Venezuela', 'iso3' => 'VEN', 'latitude' => 6.4, 'longitude' => -66.6],
            ],
            'asie' => [
                ['name' => 'Afghanistan', 'iso3' => 'AFG', 'latitude' => 33.9, 'longitude' => 67.7],
                ['name' => 'Arabie saoudite', 'iso3' => 'SAU', 'latitude' => 23.9, 'longitude' => 45.1],
                ['name' => 'Arménie', 'iso3' => 'ARM', 'latitude' => 40.1, 'longitude' => 45.0],
                ['name' => 'Azerbaïdjan', 'iso3' => 'AZE', 'latitude' => 40.1, 'longitude' => 47.6],
                ['name' => 'Bahreïn', 'iso3' => 'BHR', 'latitude' => 26.0, 'longitude' => 50.6],
                ['name' => 'Bangladesh', 'iso3' => 'BGD', 'latitude' => 23.7, 'longitude' => 90.4],
                ['name' => 'Bhoutan', 'iso3' => 'BTN', 'latitude' => 27.5, 'longitude' => 90.4],
                ['name' => 'Brunei', 'iso3' => 'BRN', 'latitude' => 4.5, 'longitude' => 114.7],
                ['name' => 'Cambodge', 'iso3' => 'KHM', 'latitude' => 12.6, 'longitude' => 104.9],
                ['name' => 'Chine', 'iso3' => 'CHN', 'latitude' => 35.9, 'longitude' => 104.2],
                ['name' => 'Chypre', 'iso3' => 'CYP', 'latitude' => 35.1, 'longitude' => 33.4],
                ['name' => 'Corée du Nord', 'iso3' => 'PRK', 'latitude' => 40.3, 'longitude' => 127.5],
                ['name' => 'Corée du Sud', 'iso3' => 'KOR', 'latitude' => 35.9, 'longitude' => 127.8],
                ['name' => 'Émirats arabes unis', 'iso3' => 'ARE', 'latitude' => 23.4, 'longitude' => 53.8],
                ['name' => 'Géorgie', 'iso3' => 'GEO', 'latitude' => 42.3, 'longitude' => 43.4],
                ['name' => 'Inde', 'iso3' => 'IND', 'latitude' => 20.6, 'longitude' => 79.1],
                ['name' => 'Indonésie', 'iso3' => 'IDN', 'latitude' => -0.8, 'longitude' => 113.9],
                ['name' => 'Irak', 'iso3' => 'IRQ', 'latitude' => 33.2, 'longitude' => 43.7],
                ['name' => 'Iran', 'iso3' => 'IRN', 'latitude' => 32.4, 'longitude' => 53.7],
                ['name' => 'Israël', 'iso3' => 'ISR', 'latitude' => 31.0, 'longitude' => 34.9],
                ['name' => 'Japon', 'iso3' => 'JPN', 'latitude' => 36.2, 'longitude' => 138.3],
                ['name' => 'Jordanie', 'iso3' => 'JOR', 'latitude' => 30.6, 'longitude' => 36.2],
                ['name' => 'Kazakhstan', 'iso3' => 'KAZ', 'latitude' => 48.0, 'longitude' => 66.9],
                ['name' => 'Kirghizistan', 'iso3' => 'KGZ', 'latitude' => 41.2, 'longitude' => 74.8],
                ['name' => 'Koweït', 'iso3' => 'KWT', 'latitude' => 29.3, 'longitude' => 47.5],
                ['name' => 'Laos', 'iso3' => 'LAO', 'latitude' => 19.9, 'longitude' => 102.5],
                ['name' => 'Liban', 'iso3' => 'LBN', 'latitude' => 33.9, 'longitude' => 35.9],
                ['name' => 'Malaisie', 'iso3' => 'MYS', 'latitude' => 4.2, 'longitude' => 101.9],
                ['name' => 'Maldives', 'iso3' => 'MDV', 'latitude' => 3.2, 'longitude' => 73.2],
                ['name' => 'Mongolie', 'iso3' => 'MNG', 'latitude' => 46.9, 'longitude' => 103.8],
                ['name' => 'Myanmar', 'iso3' => 'MMR', 'latitude' => 21.9, 'longitude' => 95.9],
                ['name' => 'Népal', 'iso3' => 'NPL', 'latitude' => 28.4, 'longitude' => 84.1],
                ['name' => 'Oman', 'iso3' => 'OMN', 'latitude' => 21.5, 'longitude' => 55.9],
                ['name' => 'Ouzbékistan', 'iso3' => 'UZB', 'latitude' => 41.4, 'longitude' => 64.6],
                ['name' => 'Pakistan', 'iso3' => 'PAK', 'latitude' => 30.4, 'longitude' => 69.3],
                ['name' => 'Palestine', 'iso3' => 'PSE', 'latitude' => 31.9, 'longitude' => 35.2],
                ['name' => 'Philippines', 'iso3' => 'PHL', 'latitude' => 12.9, 'longitude' => 121.8],
                ['name' => 'Qatar', 'iso3' => 'QAT', 'latitude' => 25.4, 'longitude' => 51.2],
                ['name' => 'Russie', 'iso3' => 'RUS', 'latitude' => 61.5, 'longitude' => 105.3],
                ['name' => 'Singapour', 'iso3' => 'SGP', 'latitude' => 1.4, 'longitude' => 103.8],
                ['name' => 'Sri Lanka', 'iso3' => 'LKA', 'latitude' => 7.9, 'longitude' => 80.8],
                ['name' => 'Syrie', 'iso3' => 'SYR', 'latitude' => 34.8, 'longitude' => 38.9],
                ['name' => 'Tadjikistan', 'iso3' => 'TJK', 'latitude' => 38.9, 'longitude' => 71.3],
                ['name' => 'Thaïlande', 'iso3' => 'THA', 'latitude' => 15.9, 'longitude' => 100.9],
                ['name' => 'Timor oriental', 'iso3' => 'TLS', 'latitude' => -8.9, 'longitude' => 125.7],
                ['name' => 'Turkménistan', 'iso3' => 'TKM', 'latitude' => 38.9, 'longitude' => 59.6],
                ['name' => 'Turquie', 'iso3' => 'TUR', 'latitude' => 38.9, 'longitude' => 35.2],
                ['name' => 'Viêt Nam', 'iso3' => 'VNM', 'latitude' => 14.1, 'longitude' => 108.3],
                ['name' => 'Yémen', 'iso3' => 'YEM', 'latitude' => 15.6, 'longitude' => 48.5],
            ],
            'europe' => [
                ['name' => 'Albanie', 'iso3' => 'ALB', 'latitude' => 41.2, 'longitude' => 20.2],
                ['name' => 'Allemagne', 'iso3' => 'DEU', 'latitude' => 51.2, 'longitude' => 10.5],
                ['name' => 'Andorre', 'iso3' => 'AND', 'latitude' => 42.5, 'longitude' => 1.5],
                ['name' => 'Autriche', 'iso3' => 'AUT', 'latitude' => 47.5, 'longitude' => 14.6],
                ['name' => 'Bélarus', 'iso3' => 'BLR', 'latitude' => 53.7, 'longitude' => 28.0],
                ['name' => 'Belgique', 'iso3' => 'BEL', 'latitude' => 50.5, 'longitude' => 4.5],
                ['name' => 'Bosnie-Herzégovine', 'iso3' => 'BIH', 'latitude' => 44.0, 'longitude' => 17.7],
                ['name' => 'Bulgarie', 'iso3' => 'BGR', 'latitude' => 42.7, 'longitude' => 25.5],
                ['name' => 'Croatie', 'iso3' => 'HRV', 'latitude' => 45.1, 'longitude' => 15.2],
                ['name' => 'Danemark', 'iso3' => 'DNK', 'latitude' => 56.3, 'longitude' => 9.5],
                ['name' => 'Espagne', 'iso3' => 'ESP', 'latitude' => 40.5, 'longitude' => -3.7],
                ['name' => 'Estonie', 'iso3' => 'EST', 'latitude' => 58.6, 'longitude' => 25.0],
                ['name' => 'Finlande', 'iso3' => 'FIN', 'latitude' => 64.0, 'longitude' => 26.0],
                ['name' => 'France', 'iso3' => 'FRA', 'latitude' => 46.2, 'longitude' => 2.2],
                ['name' => 'Grèce', 'iso3' => 'GRC', 'latitude' => 39.1, 'longitude' => 22.1],
                ['name' => 'Hongrie', 'iso3' => 'HUN', 'latitude' => 47.2, 'longitude' => 19.5],
                ['name' => 'Irlande', 'iso3' => 'IRL', 'latitude' => 53.4, 'longitude' => -8.2],
                ['name' => 'Islande', 'iso3' => 'ISL', 'latitude' => 64.9, 'longitude' => -19.0],
                ['name' => 'Italie', 'iso3' => 'ITA', 'latitude' => 41.9, 'longitude' => 12.6],
                ['name' => 'Kosovo', 'iso3' => 'XKX', 'latitude' => 42.6, 'longitude' => 20.9],
                ['name' => 'Lettonie', 'iso3' => 'LVA', 'latitude' => 56.9, 'longitude' => 24.6],
                ['name' => 'Liechtenstein', 'iso3' => 'LIE', 'latitude' => 47.2, 'longitude' => 9.6],
                ['name' => 'Lituanie', 'iso3' => 'LTU', 'latitude' => 55.2, 'longitude' => 24.0],
                ['name' => 'Luxembourg', 'iso3' => 'LUX', 'latitude' => 49.8, 'longitude' => 6.1],
                ['name' => 'Macédoine du Nord', 'iso3' => 'MKD', 'latitude' => 41.6, 'longitude' => 21.7],
                ['name' => 'Malte', 'iso3' => 'MLT', 'latitude' => 35.9, 'longitude' => 14.5],
                ['name' => 'Moldavie', 'iso3' => 'MDA', 'latitude' => 47.4, 'longitude' => 28.4],
                ['name' => 'Monaco', 'iso3' => 'MCO', 'latitude' => 43.7, 'longitude' => 7.4],
                ['name' => 'Monténégro', 'iso3' => 'MNE', 'latitude' => 42.7, 'longitude' => 19.4],
                ['name' => 'Norvège', 'iso3' => 'NOR', 'latitude' => 60.5, 'longitude' => 8.5],
                ['name' => 'Pays-Bas', 'iso3' => 'NLD', 'latitude' => 52.1, 'longitude' => 5.3],
                ['name' => 'Pologne', 'iso3' => 'POL', 'latitude' => 51.9, 'longitude' => 19.1],
                ['name' => 'Portugal', 'iso3' => 'PRT', 'latitude' => 39.4, 'longitude' => -8.2],
                ['name' => 'République tchèque', 'iso3' => 'CZE', 'latitude' => 49.8, 'longitude' => 15.5],
                ['name' => 'Roumanie', 'iso3' => 'ROU', 'latitude' => 45.9, 'longitude' => 24.9],
                ['name' => 'Royaume-Uni', 'iso3' => 'GBR', 'latitude' => 55.4, 'longitude' => -3.4],
                ['name' => 'Saint-Marin', 'iso3' => 'SMR', 'latitude' => 43.9, 'longitude' => 12.5],
                ['name' => 'Serbie', 'iso3' => 'SRB', 'latitude' => 44.0, 'longitude' => 21.0],
                ['name' => 'Slovaquie', 'iso3' => 'SVK', 'latitude' => 48.7, 'longitude' => 19.7],
                ['name' => 'Slovénie', 'iso3' => 'SVN', 'latitude' => 46.2, 'longitude' => 14.8],
                ['name' => 'Suède', 'iso3' => 'SWE', 'latitude' => 60.1, 'longitude' => 18.6],
                ['name' => 'Suisse', 'iso3' => 'CHE', 'latitude' => 46.8, 'longitude' => 8.2],
                ['name' => 'Ukraine', 'iso3' => 'UKR', 'latitude' => 48.4, 'longitude' => 31.2],
                ['name' => 'Vatican', 'iso3' => 'VAT', 'latitude' => 41.9, 'longitude' => 12.5],
            ],
            'oceanie' => [
                ['name' => 'Australie', 'iso3' => 'AUS', 'latitude' => -25.3, 'longitude' => 133.8],
                ['name' => 'Fidji', 'iso3' => 'FJI', 'latitude' => -17.7, 'longitude' => 178.1],
                ['name' => 'Kiribati', 'iso3' => 'KIR', 'latitude' => 1.9, 'longitude' => -157.4],
                ['name' => 'Îles Marshall', 'iso3' => 'MHL', 'latitude' => 7.1, 'longitude' => 171.2],
                ['name' => 'Micronésie', 'iso3' => 'FSM', 'latitude' => 6.9, 'longitude' => 158.2],
                ['name' => 'Nauru', 'iso3' => 'NRU', 'latitude' => -0.5, 'longitude' => 166.9],
                ['name' => 'Nouvelle-Zélande', 'iso3' => 'NZL', 'latitude' => -40.9, 'longitude' => 174.9],
                ['name' => 'Palaos', 'iso3' => 'PLW', 'latitude' => 7.5, 'longitude' => 134.6],
                ['name' => 'Papouasie-Nouvelle-Guinée', 'iso3' => 'PNG', 'latitude' => -6.3, 'longitude' => 143.9],
                ['name' => 'Samoa', 'iso3' => 'WSM', 'latitude' => -13.8, 'longitude' => -172.1],
                ['name' => 'Salomon', 'iso3' => 'SLB', 'latitude' => -9.6, 'longitude' => 160.2],
                ['name' => 'Tonga', 'iso3' => 'TON', 'latitude' => -21.2, 'longitude' => -175.2],
                ['name' => 'Tuvalu', 'iso3' => 'TUV', 'latitude' => -7.1, 'longitude' => 177.6],
                ['name' => 'Vanuatu', 'iso3' => 'VUT', 'latitude' => -15.4, 'longitude' => 166.9],
            ],
        ];

        foreach ($countries as $continentSlug => $items) {
            $continentId = $continents[$continentSlug]->id;

            foreach ($items as $data) {
                Country::create([
                    'continent_id' => $continentId,
                    'name' => $data['name'],
                    'iso3' => $data['iso3'],
                    'latitude' => $data['latitude'],
                    'longitude' => $data['longitude'],
                    'slug' => Str::slug($data['name']),
                ]);
            }
        }
    }
}
